name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZTNkNjMwOTEtNDVhZi00Y2M2LTk1NjQtYmYzMzJlNjk5MDNkIiwidGVuYW50X2lkIjoiMmIyMTEzY2EzNzlmOTI3NWFhNTYzZmRlZTdkMjIzYWI4MGMwMjNhOGIyMWZlNDBhYjI0ZmFjYWIxOTFjOTZlNCIsImludGVybmFsX3NlY3JldCI6ImZkMGJlOTYyLWIxYjMtNDE0OS04NDczLTIyYWQ2NDRlMDFhMyJ9.G4LLFRGiJlHbwHjB63cmJoRqNySSQrHVTgHgoHt9zKU"
JWT_SECRET="GETBLOGS"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"